CiviCooP/org.civicoop.civirules

- CRM/Civirules/Utils/PreData.php
Please see issue #47 here: https://github.com/CiviCooP/org.civicoop.civirules/issues/47
> Added ActionLog to non API entities Pre Hook.

- CRM/Civirules/Form/RuleAction.php
- CRM/CivirulesActions/Activity/Form/Activity.php
- CRM/CivirulesActions/Form/Form.php
- CRM/CivirulesActions/User/DisplayMessage.mgd.php
- CRM/CivirulesActions/User/DisplayMessage.php
- CRM/CivirulesActions/User/Form/DisplayMessage.php
- CRM/CivirulesConditions/Generic/ValueComparison.php
- templates/CRM/CivirulesActions/User/Form/DisplayMessage.tpl
- xml/Menu/civirules.xml
1) Added a String Contains condition. Possible use cases include "activity created contains word" or "contact created with first name John"
2) Added a Display Message action. Possible use cases include informing a user whenever they've created an activity containing a certain phrase, or when they've edited a user and left an important field blank.
3) Minor changes: making the exceptions unique and correcting an evident spelling mistake.
> Features: String Contains condition & Display Message action

- CRM/Civirules/Form/Rule.php
- CRM/Civirules/Form/RuleAction.php
- CRM/Civirules/Form/RuleCondition.php
- CRM/CivirulesConditions/Form/FieldValueComparison.php
- templates/CRM/Civirules/Form/RuleBlocks/ActionBlock.tpl
- templates/CRM/Civirules/Form/RuleBlocks/ConditionBlock.tpl
- templates/CRM/Civirules/Page/Rule.tpl
* fixed icons under 4.6+
* added more select2 dropdowns
> UI improvements

- CRM/CivirulesConditions/Form/FieldValueComparison.php
Fixes fallback problems with whitespace field lables
> Fix bad field lables

- CRM/Civirules/Engine.php
- CRM/Civirules/TriggerData/Post.php
Relationship based trigger wasn't working, due to some confusion with ``contact_id``. This should fix it.
> Fix relationship trigger

- CRM/Civirules/Utils/CustomDataFromPre.php
This stops an empty api request from being made and causing an error.
> Fix for issue #55 not being able to enable online registration

- CRM/CivirulesConditions/Activity/StatusChanged.mgd.php
- CRM/CivirulesConditions/Activity/StatusChanged.php
This changes add an "Activity status changed" condition which, as the name implies, allows one to test for an activity status change.
> Add an "Activity status changed" condition

- CRM/CivirulesActions/Case/Form/SetStatus.php
- CRM/CivirulesActions/Case/SetStatus.mgd.php
- CRM/CivirulesActions/Case/SetStatus.php
- templates/CRM/CivirulesActions/Case/Form/SetStatus.tpl
- xml/Menu/civirules.xml
This change adds a "Set case status" action, which allows one to set up a rule action to change a case status.
> Add "Set case status" action

- CRM/Queue/Queue/Civirules.php
> No debug information when queue operating normally

- CRM/Civirules/Page/Rule.php
This is related to Issue #123.
> Making Administer > CiviRules multisite compatible

- CRM/CivirulesConditions/Contact/HasSubtype.mgd.php
- CRM/CivirulesConditions/Contact/HasSubtype.php
- CRM/CivirulesConditions/Contact/SubtypesChanged.mgd.php
- CRM/CivirulesConditions/Contact/SubtypesChanged.php
- CRM/CivirulesConditions/Form/Contact/HasSubtype.php
- templates/CRM/CivirulesConditions/Form/Contact/HasSubtype.tpl
- xml/Menu/civirules.xml
- hasSubtype to check the subtype(s) of a Contact
- SubtypesChanged to compare subtype(s) before and after change
> Subtype Conditions :

- CRM/Civirules/BAO/Rule.php
If `civirule_trigger` has an `object_name` of "Contact", it should be triggered when `hook_civicrm_post` passes an `$objectName` of "Individual", "Household", or "Organization".
> Closes #79

- civirules.php
This hook is required for the basic_get api in later versions.
> Add entityTypes hook.

- CRM/CivirulesPostTrigger/ContactCustomDataChanged.mgd.php
- CRM/CivirulesPostTrigger/ContactCustomDataChanged.php
- CRM/CivirulesPostTrigger/IndividualCustomDataChanged.mgd.php
- CRM/CivirulesPostTrigger/IndividualCustomDataChanged.php
- CRM/CivirulesPostTrigger/OrganizationCustomDataChanged.mgd.php
- CRM/CivirulesPostTrigger/OrganizationCustomDataChanged.php
- civirules.php
Add triggers on Custom Data changed for Contact, Individual and Organization
> Triggers on Custom Data Changed for Contact, Individual and Organization

- CRM/Civirules/Form/Search/Rules.php
- civirules.php
> Makes Find CiviRules Rules custom search multisite compatible 

- CRM/CivirulesActions/Generic/Api.php
Wondering if there is any reason why you were exiting the code here. See https://github.com/CiviCooP/org.civicoop.civirules/issues/161 for background.
> throw an exception rather than an exit

- CRM/CivirulesConditions/Activity/Details.php
- info.xml
preparing for a new release. see https://github.com/CiviCooP/org.civicoop.civirules/issues/164
@jaapjansma  - is this OK for a release? If so I'll create a new release in the extensions directory...
> preparing for a new release

- CRM/CivirulesConditions/Activity/Details.php
@jaapjansma - i'm planning on creating a new release if and once this PR is merged.
> trim before comparing activity details for an exact match

- tests/phpunit/CRM/CivirulesConditions/Activity/DetailsTest.php
@kainuk - I'm adding a test for Activity.Details - can we merge?
> Adding test for activity details condition

- CRM/Civirules/ActionEngine/AbstractActionEngine.php
- CRM/Civirules/ActionEngine/Factory.php
- CRM/Civirules/ActionEngine/RuleActionEngine.php
- CRM/Civirules/Engine.php
- tests/phpunit/CRM/Civirules/ActionEngine/ActionEngineTest.php
- tests/phpunit/CRM/Civirules/EngineTest.php
Added an action engine so we can add other methods for processing actions. See #183 for more information.
> Action engine

- CRM/Civirules/Delay/DelayBasedOnDateField.php
Notice: A non well formed numeric value encountered in %s on line %d
Warning: A non-numeric value encountered in %s on line %d
> Migrating to PHP 7.1.x

- CRM/CivirulesConditions/Address/IsUnique.mgd.php
- CRM/CivirulesConditions/Address/IsUnique.php
@jaapjansma  Sorry, I didn't check the last commit enough.
Moving to a subdirectory (Address) needs some changes in the code.
> Fix Address IsUnique condition

- CRM/Civirules/TriggerData/TriggerData.php
- CRM/Civirules/Utils/PreData.php
- CRM/CivirulesConditions/Generic/FieldChanged.php
> make custom fields accessible for field change comparison

- docs/databasetables.md
The word "holding" on the third line should be after the pipe.
> Fixed minor formatting issue.
